name: htcds
description: Human Trafficking Case Data Standard (HTCDS) objects, for easy creation, storage and transmission of case data related to human trafficking.
version: 1.0.1
repository: https://github.com/0xdir/htcds_dart

funding:
  - https://github.com/sponsors/0xdir
topics:
  - data
  - schema
  - humanitarian
  - standards

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0